### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by fare**

### CODE REVIEW

**Comment by MathieuDutSik** [comment]
The operation `make docker-build-all` does not work on this branch. The error is
```Error: Library "ppx_deriving_yojson.runtime" not found.
Hint: try: dune external-lib-deps --missing src/legilogic_lib/legilogic_lib.cmxs src/legilogic_ethereum/legilogic_ethereum.cmxs src/legilogic_ethereum/ethereum_prefunder.exe src/alacris_lib/alacris_lib.cmxs src/alacris_lib/side_chain_server.exe src/alacris_contract/setup_contract.exe src/alacris_client/side_chain_client.exe src/alacris_client/side_chain_client_test.exe src/toplevel.exe
make: *** [Makefile:183: build_all] Error 1
ERROR: Service 'alacris_side_chain_manager' failed to build: The command '/bin/sh -c make' returned a non-zero code: 2
docker-compose -f docker/docker-compose.yml build --no-cache failed with exit code 0
Makefile:286: recipe for target 'docker-build-all' failed
make: *** [docker-build-all] Error 1
mathieu@mathieu-Inspiron-5767:~/GITall/GIT/legicash-facts$ ```

**Comment by MathieuDutSik** [comment]
Some warnings while compiling: ```File "src/legilogic_ethereum/contract_config.mli", line 19, characters 0-77:
Warning 32: unused value contract_config_of_creation_hash.```

**Comment by fare** [comment]
The above issues should now be fixed. Thanks.

**Comment by MathieuDutSik** [comment]
The modifications done to **side_chain_action.ml** are not correct.
The **setup_contract.exe** NEEDS to create the file /tmp/contract_address.json
in order that the side_chain_server and side_chain_client know where to get their
contract.

**Comment by fare** [comment]
IIUC, the current status of this branch seems to be that the tests interact badly with the server, because parts of our code use global `ref`'s instead of per-operator data structure. @MathieuDutSik can you give details in this pull request before the data is swapped out? That will make it easier for whoever completes this work, if it ever happens.

**Comment by MathieuDutSik** [comment]
Hi Fare,

the problem is that since you changed everything, we had to work from the
broken system
and make it work. Thus, I cannot tell you where things went wrong on that
particular problem.
I expressed my scepticism about your approach at the time.

Now, the situation is worse since I cannot even test the software:
--------------------------------------------------------
(base) mathieu@mathieu-Inspiron-5767:~/GITall/GIT/legicash-facts$ make
docker-reset-state
Resetting Alacris states
Resetting configuration
docker: Error response from daemon: network docker_legicash-demo not found.
ERRO[0002] error waiting for container: context canceled
Makefile:334: recipe for target 'docker-reset-state' failed
make: *** [docker-reset-state] Error 125
----------------------------------------------------------
And since Vedran is out, there is no immediate way to address the problem.

  Mathieu

**Pull request merged**
